# Generated by Django 5.2.8 on 2025-11-26 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skills', models.JSONField(default=list)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('hours_contributed', models.PositiveIntegerField(default=0)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
