# Generated by Django 5.2.8 on 2025-11-30 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('required_skills', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skills', models.JSONField(default=list)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('department_preferences', models.JSONField(default=list)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('is_in_remote_area', models.BooleanField(default=False)),
            ],
        ),
    ]
